apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yo-backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yogesh-shelke-nttd/argo-servicemesh
    targetRevision: main
    path: backend-app
  destination:
    server: https://kubernetes.default.svc
    namespace: yo-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - Validate=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 1m