apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-ingressgateway
  namespace: yo-istio-ingress
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch